export const pageStyles = {
  container: { padding: '30px', backgroundColor: 'var(--bg)', minHeight: '100vh', color: 'var(--text)', fontFamily: 'Inter, sans-serif' },
  loading: { color: 'var(--muted-2)', textAlign: 'center', marginTop: '20%', letterSpacing: '2px' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', flexWrap: 'wrap', gap: '12px' },
  headerLeft: { display: 'flex', alignItems: 'center', gap: '16px' },
  headerRight: { display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' },
  title: { fontSize: '20px', fontWeight: '900', margin: 0 },
  backBtn: { background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text)', padding: '8px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center' },
  searchBox: { display: 'flex', alignItems: 'center', gap: '10px', backgroundColor: 'var(--surface)', padding: '8px 15px', borderRadius: '8px', border: '1px solid var(--border)' },
  searchInput: { background: 'none', border: 'none', color: 'var(--text)', outline: 'none', fontSize: '13px', width: '200px' },
  primaryBtn: { backgroundColor: '#0055ff', color: '#fff', border: 'none', padding: '10px 18px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px' },
  secondaryBtn: { backgroundColor: 'var(--surface-2)', border: '1px solid var(--accent)', color: 'var(--text)', padding: '10px 18px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 4px 12px var(--accent-shadow)', transition: 'all 0.3s ease' },
  tabBar: { display: 'flex', gap: '8px', marginBottom: '20px', flexWrap: 'wrap' },
  tab: { padding: '10px 18px', borderRadius: '8px', border: '1px solid var(--border-strong)', background: 'var(--surface)', color: 'var(--muted)', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px' },
  tabActive: { padding: '10px 18px', borderRadius: '8px', border: '1px solid var(--accent)', background: 'var(--accent-soft)', color: 'var(--text)', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px' },
  gridSection: { borderRadius: '12px', overflow: 'hidden' },
  gridHeader: { display: 'flex', justifyContent: 'flex-end', padding: '14px 18px 0 18px', gap: '10px', backgroundColor: 'var(--bg)', borderBottom: '1px solid var(--border)' },
  settingsBtn: { backgroundColor: 'var(--surface)', border: '1px solid var(--border-strong)', color: 'var(--text)', padding: '9px 14px', borderRadius: '8px', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '8px', fontSize: '12px' },
  filterRow: { display: 'flex', gap: '10px', marginBottom: '16px', flexWrap: 'wrap', alignItems: 'center' },
  select: { backgroundColor: 'var(--surface)', border: '1px solid var(--border-strong)', color: 'var(--text)', padding: '8px 12px', borderRadius: '8px', fontSize: '12px', outline: 'none' },
  modalOverlay: { position: 'fixed', inset: 0, backgroundColor: 'var(--overlay)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 9999, padding: '20px' },
  modalContent: { backgroundColor: 'var(--surface)', color: 'var(--text)', padding: '28px', borderRadius: '15px', width: '100%', maxWidth: '640px', border: '1px solid var(--border-strong)', maxHeight: '90vh', overflowY: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid var(--border)', paddingBottom: '15px' },
  form: { display: 'flex', flexDirection: 'column', gap: '16px' },
  inputGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' },
  label: { fontSize: '10px', color: 'var(--muted-2)', fontWeight: 'bold', letterSpacing: '0.5px', marginBottom: '4px', display: 'block' },
  formInput: { width: '100%', backgroundColor: 'var(--surface-3)', border: '1px solid var(--border-strong)', padding: '11px', borderRadius: '8px', color: 'var(--text)', fontSize: '13px', outline: 'none', boxSizing: 'border-box' },
  readOnlyInput: { width: '100%', backgroundColor: 'var(--surface-2)', border: '1px solid var(--border-strong)', padding: '11px', borderRadius: '8px', color: 'var(--muted-2)', fontSize: '13px', boxSizing: 'border-box' },
  submitBtn: { backgroundColor: '#0055ff', color: '#fff', border: 'none', padding: '14px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', marginTop: '8px' },
  actionBtn: { backgroundColor: 'var(--surface)', border: '1px solid var(--border-strong)', color: 'var(--accent)', padding: '5px 10px', borderRadius: '4px', cursor: 'pointer', fontSize: '10px', fontWeight: 'bold', marginRight: '4px' },
  badgeActive: { backgroundColor: '#166534', color: '#fff', padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold', textAlign: 'center' },
  badgeInactive: { backgroundColor: '#7f1d1d', color: '#fff', padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold', textAlign: 'center' },
  chartBox: { backgroundColor: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '12px', padding: '24px', marginBottom: '20px' },
};
