export const pageStyles = {
  container: { padding: '30px', backgroundColor: '#050505', minHeight: '100vh', color: '#fff', fontFamily: 'Inter, sans-serif' },
  loading: { color: '#666', textAlign: 'center', marginTop: '20%', letterSpacing: '2px' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', flexWrap: 'wrap', gap: '12px' },
  headerLeft: { display: 'flex', alignItems: 'center', gap: '16px' },
  headerRight: { display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' },
  title: { fontSize: '20px', fontWeight: '900', margin: 0 },
  backBtn: { background: '#0a0a0a', border: '1px solid #111', color: '#fff', padding: '8px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center' },
  searchBox: { display: 'flex', alignItems: 'center', gap: '10px', backgroundColor: '#0a0a0a', padding: '8px 15px', borderRadius: '8px', border: '1px solid #111' },
  searchInput: { background: 'none', border: 'none', color: '#fff', outline: 'none', fontSize: '13px', width: '200px' },
  primaryBtn: { backgroundColor: '#0055ff', color: '#fff', border: 'none', padding: '10px 18px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px' },
  secondaryBtn: { backgroundColor: '#111', border: '1px solid #0055ff', color: '#fff', padding: '10px 18px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 4px 12px rgba(0, 85, 255, 0.3)', transition: 'all 0.3s ease' },
  tabBar: { display: 'flex', gap: '8px', marginBottom: '20px', flexWrap: 'wrap' },
  tab: { padding: '10px 18px', borderRadius: '8px', border: '1px solid #222', background: '#0a0a0a', color: '#888', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px' },
  tabActive: { padding: '10px 18px', borderRadius: '8px', border: '1px solid #0055ff', background: '#0055ff22', color: '#fff', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px' },
  gridSection: { borderRadius: '12px', overflow: 'hidden' },
  gridHeader: { display: 'flex', justifyContent: 'flex-end', padding: '14px 18px 0 18px', gap: '10px', backgroundColor: '#050505', borderBottom: '1px solid #111' },
  settingsBtn: { backgroundColor: '#0a0a0a', border: '1px solid #222', color: '#fff', padding: '9px 14px', borderRadius: '8px', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '8px', fontSize: '12px' },
  filterRow: { display: 'flex', gap: '10px', marginBottom: '16px', flexWrap: 'wrap', alignItems: 'center' },
  select: { backgroundColor: '#0a0a0a', border: '1px solid #222', color: '#fff', padding: '8px 12px', borderRadius: '8px', fontSize: '12px', outline: 'none' },
  modalOverlay: { position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.9)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 9999, padding: '20px' },
  modalContent: { backgroundColor: '#0a0a0a', padding: '28px', borderRadius: '15px', width: '100%', maxWidth: '640px', border: '1px solid #1a1a1a', maxHeight: '90vh', overflowY: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid #111', paddingBottom: '15px' },
  form: { display: 'flex', flexDirection: 'column', gap: '16px' },
  inputGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' },
  label: { fontSize: '10px', color: '#666', fontWeight: 'bold', letterSpacing: '0.5px', marginBottom: '4px', display: 'block' },
  formInput: { width: '100%', backgroundColor: '#000', border: '1px solid #1a1a1a', padding: '11px', borderRadius: '8px', color: '#fff', fontSize: '13px', outline: 'none', boxSizing: 'border-box' },
  readOnlyInput: { width: '100%', backgroundColor: '#111', border: '1px solid #1a1a1a', padding: '11px', borderRadius: '8px', color: '#666', fontSize: '13px', boxSizing: 'border-box' },
  submitBtn: { backgroundColor: '#0055ff', color: '#fff', border: 'none', padding: '14px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', marginTop: '8px' },
  actionBtn: { backgroundColor: '#0a0a0a', border: '1px solid #222', color: '#0055ff', padding: '5px 10px', borderRadius: '4px', cursor: 'pointer', fontSize: '10px', fontWeight: 'bold', marginRight: '4px' },
  badgeActive: { backgroundColor: '#166534', color: '#fff', padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold', textAlign: 'center' },
  badgeInactive: { backgroundColor: '#7f1d1d', color: '#fff', padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold', textAlign: 'center' },
  chartBox: { backgroundColor: '#0a0a0a', border: '1px solid #111', borderRadius: '12px', padding: '24px', marginBottom: '20px' },
};
