/**
 * PWA Utilities — Service Worker Registration, Push Notifications, WebAuthn
 */

// ──────────────────────────────────────────────
// 1. SERVICE WORKER REGISTRATION
// ──────────────────────────────────────────────

/**
 * Register the service worker generated by vite-plugin-pwa.
 * Uses dynamic import of virtual:pwa-register so that if the
 * virtual module fails to resolve, the app still loads gracefully
 * (instead of crashing with a blank white screen).
 *
 * Returns the ServiceWorkerRegistration via the onRegistered callback.
 * The returned object has a `reload` function to force-update.
 *
 * @returns {Promise<{reload: Function, registration: ServiceWorkerRegistration|null}>}
 */
export async function registerSW() {
  if (!('serviceWorker' in navigator)) {
    console.warn('[PWA] Service Worker not supported');
    return { reload: () => {}, registration: null };
  }

  let swRegistration = null;

  try {
    // Dynamic import — if virtual:pwa-register fails, we catch and return gracefully
    const { registerSW: pwaRegisterSW } = await import(
      /* @vite-ignore */ 'virtual:pwa-register'
    ).catch((err) => {
      console.warn('[PWA] virtual:pwa-register module not available, skipping SW registration:', err);
      return { registerSW: null };
    });

    if (typeof pwaRegisterSW !== 'function') {
      console.warn('[PWA] pwaRegisterSW is not a function, skipping registration');
      return { reload: () => {}, registration: null };
    }

    const reload = pwaRegisterSW({
      onNeedRefresh() {
        console.log('[PWA] New content available; refreshing...');
        reload(true);
      },
      onOfflineReady() {
        console.log('[PWA] App ready for offline use');
      },
      onRegistered(registration) {
        swRegistration = registration;
        console.log('[PWA] Service Worker registered:', registration);
      },
      onRegisterError(error) {
        console.error('[PWA] Service Worker registration failed:', error);
      },
    });

    // Wait a tick for onRegistered to fire
    await new Promise(resolve => setTimeout(resolve, 100));

    return { reload, registration: swRegistration };
  } catch (err) {
    console.error('[PWA] Service Worker registration error:', err);
    return { reload: () => {}, registration: null };
  }
}

/**
 * Get the current active service worker registration (if any).
 * Useful after registerSW() has been called.
 */
export async function getRegistration() {
  if (!('serviceWorker' in navigator)) return null;
  try {
    return await navigator.serviceWorker.getRegistration();
  } catch {
    return null;
  }
}

// ──────────────────────────────────────────────
// 2. WEB PUSH NOTIFICATIONS
// ──────────────────────────────────────────────

/**
 * Convert a base64url string to a Uint8Array (for VAPID key)
 */
function urlBase64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/');
  const rawData = window.atob(base64);
  return new Uint8Array([...rawData].map((char) => char.charCodeAt(0)));
}

/**
 * Request notification permission and subscribe to push
 * @param {ServiceWorkerRegistration} registration
 * @param {string} vapidPublicKey - VAPID public key
 * @returns {Promise<PushSubscription|null>}
 */
export async function subscribeToPush(registration, vapidPublicKey) {
  if (!('Notification' in window)) {
    console.warn('[PWA] Notifications not supported');
    return null;
  }

  // Request permission
  let permission = Notification.permission;
  if (permission === 'default') {
    permission = await Notification.requestPermission();
  }

  if (permission !== 'granted') {
    console.warn('[PWA] Notification permission denied');
    return null;
  }

  if (!registration || !registration.pushManager) {
    console.warn('[PWA] Push Manager not available');
    return null;
  }

  try {
    const existingSubscription = await registration.pushManager.getSubscription();
    if (existingSubscription) {
      console.log('[PWA] Already subscribed to push');
      return existingSubscription;
    }

    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
    });

    console.log('[PWA] Push subscription successful');
    return subscription;
  } catch (err) {
    console.error('[PWA] Push subscription failed:', err);
    return null;
  }
}

/**
 * Unsubscribe from push notifications
 * @param {ServiceWorkerRegistration} registration
 */
export async function unsubscribeFromPush(registration) {
  try {
    const subscription = await registration.pushManager.getSubscription();
    if (subscription) {
      await subscription.unsubscribe();
      console.log('[PWA] Unsubscribed from push');
    }
  } catch (err) {
    console.error('[PWA] Unsubscribe failed:', err);
  }
}

// ──────────────────────────────────────────────
// 3. WEBAUTHN / BIOMETRIC AUTHENTICATION
// ──────────────────────────────────────────────

/**
 * Check if WebAuthn is supported
 */
export function isWebAuthnSupported() {
  return (
    typeof window.PublicKeyCredential !== 'undefined' &&
    typeof navigator.credentials !== 'undefined'
  );
}

/**
 * Check if the device has a platform authenticator (fingerprint/face)
 */
export async function isPlatformAuthenticatorAvailable() {
  if (!isWebAuthnSupported()) return false;
  try {
    const available = await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
    return available;
  } catch {
    return false;
  }
}

/**
 * Register a new biometric credential (called after email/password login)
 * @param {string} userId - Firebase UID
 * @param {string} userName - User email or display name
 * @returns {Promise<{credentialId: string, rawId: string}|null>}
 */
export async function registerBiometricCredential(userId, userName) {
  if (!isWebAuthnSupported()) {
    console.warn('[WebAuthn] Not supported on this device');
    return null;
  }

  const challenge = crypto.getRandomValues(new Uint8Array(32));

  const publicKeyCredentialCreationOptions = {
    challenge,
    rp: {
      name: 'KAC OFFICIAL',
      id: window.location.hostname,
    },
    user: {
      id: new TextEncoder().encode(userId),
      name: userName,
      displayName: userName.split('@')[0] || 'User',
    },
    pubKeyCredParams: [
      { alg: -7, type: 'public-key' },   // ES256
      { alg: -257, type: 'public-key' },  // RS256
    ],
    authenticatorSelection: {
      authenticatorAttachment: 'platform',
      userVerification: 'required',
      residentKey: 'required',
    },
    timeout: 60000,
    attestation: 'none',
  };

  try {
    const credential = await navigator.credentials.create({
      publicKey: publicKeyCredentialCreationOptions,
    });

    const credentialData = {
      credentialId: credential.id,
      rawId: arrayBufferToBase64(credential.rawId),
    };

    // Store credential ID in localStorage for this user
    const stored = JSON.parse(localStorage.getItem('kac_webauthn_creds') || '{}');
    stored[userId] = credentialData;
    localStorage.setItem('kac_webauthn_creds', JSON.stringify(stored));

    console.log('[WebAuthn] Credential registered successfully');
    return credentialData;
  } catch (err) {
    console.error('[WebAuthn] Registration failed:', err);
    return null;
  }
}

/**
 * Authenticate using a biometric credential
 * @param {string} userId - Firebase UID
 * @returns {Promise<{credentialId: string, rawId: string}|null>}
 */
export async function authenticateWithBiometric(userId) {
  if (!isWebAuthnSupported()) {
    console.warn('[WebAuthn] Not supported on this device');
    return null;
  }

  // Retrieve stored credential
  const stored = JSON.parse(localStorage.getItem('kac_webauthn_creds') || '{}');
  const cred = stored[userId];
  if (!cred) {
    console.warn('[WebAuthn] No stored credential found for this user');
    return null;
  }

  const challenge = crypto.getRandomValues(new Uint8Array(32));

  const publicKeyCredentialRequestOptions = {
    challenge,
    allowCredentials: [
      {
        id: base64ToArrayBuffer(cred.rawId),
        type: 'public-key',
        transports: ['internal'],
      },
    ],
    userVerification: 'required',
    timeout: 60000,
  };

  try {
    const assertion = await navigator.credentials.get({
      publicKey: publicKeyCredentialRequestOptions,
    });

    console.log('[WebAuthn] Biometric authentication successful');
    return {
      credentialId: assertion.id,
      rawId: arrayBufferToBase64(assertion.rawId),
    };
  } catch (err) {
    console.error('[WebAuthn] Authentication failed:', err);
    return null;
  }
}

// ──────────────────────────────────────────────
// 4. OFFLINE DETECTION
// ──────────────────────────────────────────────

/**
 * Listen for online/offline status changes
 * @param {function(boolean)} callback - receives isOnline boolean
 * @returns {function()} cleanup function
 */
export function onOnlineStatus(callback) {
  const handleOnline = () => callback(true);
  const handleOffline = () => callback(false);

  window.addEventListener('online', handleOnline);
  window.addEventListener('offline', handleOffline);

  // Initial call
  callback(navigator.onLine);

  return () => {
    window.removeEventListener('online', handleOnline);
    window.removeEventListener('offline', handleOffline);
  };
}

// ──────────────────────────────────────────────
// 5. TWA MODE DETECTION
// ──────────────────────────────────────────────

/**
 * Detect if the app is running as a Trusted Web Activity (TWA) / Android app.
 * TWA runs in standalone mode with `display-mode: standalone`.
 * Also checks `document.referrer` for android-app protocol as fallback.
 * @returns {boolean}
 */
export function isTwaMode() {
  try {
    // Primary check: standalone display mode (used by TWA)
    if (window.matchMedia('(display-mode: standalone)').matches) {
      return true;
    }
    // Fallback: check referrer for android-app protocol
    if (document.referrer && document.referrer.includes('android-app://')) {
      return true;
    }
  } catch {
    // Ignore errors
  }
  return false;
}

// ──────────────────────────────────────────────
// 6. UTILITY HELPERS
// ──────────────────────────────────────────────

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

function base64ToArrayBuffer(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes.buffer;
}